name: report-codecov
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.18
    
    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: |
        go test -cover -coverprofile=coverage.out -v -coverpkg=./... -count=1 ./...
        go tool cover -func=coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
